fix(prepush): adjusts pre-commit to run tests in shell
TeamProductionSystem/Team_Production_System_BE pull request #181
Opened 2023-11-02 20:46 UTC by esparr

## **Pull Request Template**

### **1. Targeted Issue** ###

(Issue #167)[https://trello.com/c/FEvL708r]
(Issue #169)[https://trello.com/c/cA85T9PN] 

### **2. Overview of Solution** ###

This PR addresses two tickets, see above. 

I added in the pre-push documentation and also am offering up a solution to demonstrating outputs without compromising the ability to easily copy code from the README.md on Github. I am open to feedback on the implementation. 

This also solves an issue I was experiencing with Github Desktop when running pre-push before pushing up to Github. The solution was to make sure the tests were running in pipenv shell.

@jimbandrews assisted with this solution

### **3. Tools Used** ###

`pipenv run`

### **4. Testing Strategy** ###

Tried to run this with Github Desktop and from shell in terminal. Both successfully ran the tests. 

### **5. Future Implications** ###

### **6. Screenshots** ###

Preview mode:
<img width="591" alt="Screen Shot 2023-11-02 at 3 04 22 PM" src="https://github.com/TeamProductionSystem/Momentors_Backend/assets/14296669/a2d2d07f-ea04-41f1-b830-07fffd4bb88f">

Markdown:
<img width="529" alt="Screen Shot 2023-11-02 at 3 05 00 PM" src="https://github.com/TeamProductionSystem/Momentors_Backend/assets/14296669/f3f9ecee-ffab-476f-a7db-1670d97af4c6">

### **7. Code Reviewers** ###

@jimbandrews @GitLukeW 

---

Before you go...

- [ ]  I have linked the relevant issue
- [ ]  I have provided an overview of my solution
- [ ]  I have shared the tools I've used
- [ ]  I have outlined my testing strategy
- [ ]  I have considered future implications of my changes
- [ ]  I have included relevant screenshots
- [ ]  I have kept my team in the loop

---

### Big high-fives for your incredible pull request! We're thrilled to have you as a contributor! Our team will dig into your proposed changes and give you some feedback or merge them if they're good to go. Your contributions mean the world to us!

2023-11-02 20:53 UTC, esparr commented on Pipfile.lock
@GitLukeW During the process of debugging, I uninstalled and reinstalled celery. When I did this, I also ran pipenv install and it looks like it updated boto3 as well. Do you think this is going to cause an issue? If so I can work on reverting it.

2023-11-03 11:55 UTC, jimbandrews approved these changes
Tested out locally, and it works. Good catch!

2023-11-11 15:56 UTC, GitLukeW requested changes
Looks like this has merge conflicts from the previous PR.

2023-11-13 19:37 UTC, GitLukeW approved these changes
Thanks!

2023-11-13 19:37 UTC, merged